name: kushal_portfolio
description: "Portfolio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  url_launcher: ^6.3.0
  fluttertoast: ^8.2.6
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  ios: true
  web: true
  android: true
  color: "#1E1E28"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/